from pathlib import Path
import re,base64,json,hashlib
root=Path(__file__).resolve().parent.parent
original=(root/'assets/logo-original.jpg').read_bytes()
svg='<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="200" height="200" viewBox="0 0 200 200"><title>Directo Producciones · versión blanca fiel al JPG original</title><defs><filter id="ink" color-interpolation-filters="sRGB" x="0" y="0" width="100%" height="100%"><feColorMatrix type="matrix" values="0 0 0 0 1  0 0 0 0 1  0 0 0 0 1  -0.2785 -0.9369 -0.0946 0 1.31"/><feComponentTransfer><feFuncA type="linear" slope="1.02" intercept="-0.02"/></feComponentTransfer></filter></defs><image width="200" height="200" preserveAspectRatio="xMidYMid meet" filter="url(#ink)" xlink:href="data:image/jpeg;base64,'+base64.b64encode(original).decode()+'"/></svg>'
(root/'assets/logo-white.svg').write_text(svg)
arrow='<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14m-6-6 6 6-6 6"/></svg>'
paths=['<path d="M4 20V8l8-4 8 4v12M2 20h20M8 10v4m8-4v4M10 20v-3h4v3"/>','<path d="M5 4v16M12 4v16M19 4v16"/><circle cx="5" cy="9" r="2"/><circle cx="12" cy="15" r="2"/><circle cx="19" cy="7" r="2"/>','<rect x="3" y="4" width="18" height="13" rx="1"/><path d="M9 21h6m-3-4v4m-2-13 5 3-5 3Z"/>']
stage='<div class="signal-stage signal-flow" data-enter="160" role="group" aria-label="Recorrido de señal: evento, realización y emisión"><div class="signal-flow-heading"><p class="eyebrow">El recorrido de la señal</p><h2>Del evento a la audiencia.</h2></div><ol class="signal-flow-steps">'
for i,(label,desc)in enumerate([('Evento','Lo que sucede.'),('Realización','Cómo se cuenta.'),('Emisión','Lo que llega a la audiencia.')]):
 stage+='<li><div class="flow-icon"><svg class="icon" viewBox="0 0 24 24" aria-hidden="true">'+paths[i]+'</svg></div><div class="flow-content"><p class="flow-number">0'+str(i+1)+'</p><h3>'+label+'</h3><p>'+desc+'</p></div>'+('<span class="flow-link" aria-hidden="true">'+arrow+'</span>'if i<2 else'')+'</li>'
stage+='</ol></div>'
for name in ['index.html','desktop.html','mobile.html']:
 p=root/name;s=p.read_text()
 s=re.sub(r'<div class="signal-stage" data-enter="160">.*?</div></section>',stage+'</section>',s,flags=re.S)
 s=re.sub(r'\n<div class="signal-explainer">.*?</div></section>','</section>',s,flags=re.S)
 s=s.replace('Tu evento.<br>En directo.','Tu evento.<br>En streaming.').replace('El directo,<br>con sentido.','El evento,<br>en pantalla.').replace('Directo<br>en cifras.','Nuestra<br>trayectoria.').replace('El directo,<br>desde el otro lado.','Así lo<br>cuentan.').replace('De la idea al directo','De la idea a la emisión').replace('llegue el directo.','llegue la emisión.')
 for person in ['rafael_gonzalez','jose_luis_contreras']:
  cls='rafael'if person=='rafael_gonzalez'else'jose'
  s=re.sub(r'<img src="assets/portraits/'+person+r'.jpg" alt="([^"]+)">',r'<span class="testimonial-avatar avatar-'+cls+r'"><img src="assets/portraits/'+person+r'.jpg" alt="\1"></span>',s)
 s=re.sub(r'<img src="assets/logo-original.jpg" alt="([^"]+)" width="(\d+)" height="(\d+)">',lambda m:'<img class="brand-logo brand-logo-blue" src="assets/logo-original.jpg" alt="'+m[1]+'" width="'+m[2]+'" height="'+m[3]+'"><img class="brand-logo brand-logo-white" src="assets/logo-white.svg" alt="'+m[1]+'" width="'+m[2]+'" height="'+m[3]+'">',s)
 if 'refinements-01/refinements.css'not in s:s=s.replace('<link rel="stylesheet" href="style.css">','<link rel="stylesheet" href="style.css"><link rel="stylesheet" href="refinements-01/refinements.css">')
 p.write_text(s)
# Reuse the current approved quotes/process; rebuild only the disliked identity composition.
p=root/'suite/build-suite.py';s=p.read_text()
old=next(l for l in s.splitlines()if l.startswith('about=hero('))
new='''about=hero('Quiénes somos','Directo<br>Producciones.','Streaming, comunicación y marketing digital. Empecemos por lo que quieres contar.')+'<section class="about-working section pad" data-section="Quiénes somos · forma de trabajar"><div class="about-working-intro"><div><p class="eyebrow">Nuestra forma de trabajar</p><h2>Primero,<br>tu proyecto.</h2></div><div><p>Contenido, formato y audiencia. Tres preguntas para preparar la conversación sobre tu proyecto.</p></div></div><div class="about-working-body"><div class="about-questions"><div><span>01</span><h3>¿Qué quieres contar?</h3><p>El mensaje y la intención del proyecto.</p></div><div><span>02</span><h3>¿Cómo quieres contarlo?</h3><p>El formato, la fecha y el lugar.</p></div><div><span>03</span><h3>¿A quién quieres llegar?</h3><p>La audiencia y el canal de emisión.</p></div></div><aside class="about-people"><p class="eyebrow">Quién está detrás</p><h3>Personas<br>y funciones.</h3><p class="team-pending">[Presentación del equipo y sus funciones, pendiente de aprobación editorial.]</p><p class="content-note">Se incorporarán nombres, funciones y fotografías cuando estén validados.</p><a class="text-link" href="'+link('contacto')+'">Hablemos de tu proyecto '+icons['arrow']+'</a></aside></div></section>'+contact'''
s=s.replace(old,new)
s=s.replace('re.search(r\'<div class="signal-stage".*?</div></section>\',home,re.S).group().replace(\'class="signal-stage"\',\'class="signal-stage compact-signal"\')','re.search(r\'<div class="signal-stage signal-flow".*?</div></section>\',home,re.S).group().replace(\'class="signal-stage signal-flow"\',\'class="signal-stage signal-flow compact-flow"\')')
# Source logo appearances use the same faithful monochrome on dark, not any client/foto filter.
s=s.replace('<link rel="stylesheet" href="../style.css">','<link rel="stylesheet" href="../style.css"><link rel="stylesheet" href="../refinements-01/refinements.css">')
# Preserve the existing index's real Figma links, without another capture.
s=s.replace("(out/'index.html').write_text(","old_index=(out/'index.html').read_text() if (out/'index.html').exists() else ''\nfigma_links=re.search(r'<section style=\"margin-top:48px\">.*?</section>',old_index,re.S)\n(out/'index.html').write_text(")
s=s.replace("+nav+'</div></body></html>')","+nav+(figma_links.group() if figma_links else '')+'</div></body></html>')")
p.write_text(s)
# Guide: apply the same logo rule and add the shared avatar pattern to existing section 07.
p=root/'suite/build-guide.py';s=p.read_text().replace('<link rel="stylesheet" href="../style.css">','<link rel="stylesheet" href="../style.css"><link rel="stylesheet" href="../refinements-01/refinements.css">')
s=s.replace('En directo.','En streaming.').replace('El directo, con sentido.','El evento, en pantalla.')
s=s.replace('<div class="guide-safety"><img src="../assets/logo-original.jpg" alt="Logo original completo 200×200"><p>Logo JPG original 1:1 completo, sin vectorizar, recolorear ni recortar. Mantener área de seguridad. Sobre oscuro usar apoyo blanco; no invertir la marca. Logos de clientes: contain, proporción natural, balance óptico; 16 clientes autorizados en D-42.</p></div>', '<div class="guide-safety"><div class="brand"><img class="brand-logo brand-logo-blue" src="../assets/logo-original.jpg" alt="Directo Producciones azul · original"><img class="brand-logo brand-logo-white" src="../assets/logo-white.svg" alt="Directo Producciones blanco · máscara fiel del original"></div><p>Marca azul sobre claro; blanca y transparente sobre oscuro, autorizada expresamente en este feedback. Geometría y proporciones del JPG conservadas; máscara raster, no vectorización ni rediseño. Clientes y fotos conservan sus colores originales.</p></div><div class="avatar-guide"><div><span class="testimonial-avatar avatar-rafael"><img src="../assets/portraits/rafael_gonzalez.jpg" alt="Rafael González"></span><p>Rafael González</p></div><div><span class="testimonial-avatar avatar-jose"><img src="../assets/portraits/jose_luis_contreras.jpg" alt="José Luis Contreras"></span><p>José Luis Contreras</p></div></div><p>Avatar circular de 80 px. Misma escala óptica mediante recortes por persona; sin deformación ni generación. Testimonios y atribuciones completos se conservan.</p>')
s=s.replace('Logo corporativo independiente, sin sustituir su wordmark.','Logo corporativo independiente, con versión blanca fiel para oscuro.')
p.write_text(s)
(root/'refinements-01/crop-spec.json').write_text(json.dumps({'sizePx':80,'rafael':{'source':'assets/portraits/rafael_gonzalez.jpg','sourceSize':[800,800],'crop':[160,0,480,480],'faceReference':[305,25,205,315]},'jose':{'source':'assets/portraits/jose_luis_contreras.jpg','sourceSize':[1030,455],'crop':[350,0,248,248],'faceReference':[427,22,101,165]},'sourceLogoSha256':hashlib.sha256(original).hexdigest(),'logoMethod':'SVG deterministic luminance mask of embedded original JPG. No letter geometry recreated. White alpha derived from ink only.'},ensure_ascii=False,indent=2))
print('Fuentes corregidas; ninguna escritura/captura Figma ejecutada.')
