from pathlib import Path
import json,hashlib,html
root=Path(__file__).resolve().parents[1];out=root/'refinements-01';ev=out/'evidence'
load=lambda p:json.loads(p.read_text())
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
qa=load(ev/'verification.json');routes=load(ev/'navigation-motion.json');contrast=load(ev/'contrast.json');assets=load(ev/'assets-verification.json')
frames={'inicio-claro-desktop':'35:2','inicio-claro-mobile':'37:2','inicio-oscuro':'41:2','servicios':'42:2','clientes':'43:2','quienes-somos':'44:2','blog':'45:2','articulo':'46:2','contacto':'47:2','404':'48:2','cookies':'49:2','privacidad':'50:2','aviso-legal':'51:2','guia':'53:2'}
url=lambda id:'https://www.figma.com/design/t9eDMrakGNb7B5LbRkozeR?node-id='+id.replace(':','-')
source={'source':'https://www.directoproducciones.com/quienes-somos/','consulted':'2026-10-08','authorization':'Instrucción expresa de Jesús: aprovechar contenido de la antigua web en Quiénes somos. Uso en borrador de diseño; no aprobación nueva para producción.','reused':['Productora especializada en streaming de eventos','Equipo multidisciplinar de comunicación y marketing online','Realización televisiva y TV online','Comunicación corporativa y gabinete de prensa','Redes sociales, SEO, SEM, diseño publicitario y gestión de marca'],'omitted':['Pertenencia a Nueva Información Local SL sin validación actual','Confianza/profesionalidad 100 %','Garantías de presencia en medios, ganar seguidores y primer puesto en buscadores','Respuesta en menos de 24 horas','Nombres, funciones, retratos y años de equipo no autorizados'],'factsFile':'/home/jesus/Workspace/_Proyectos-Trabajo/directo_producciones_landing_page_1.0/content/facts.yaml','factsFileSha256':sha(Path('/home/jesus/Workspace/_Proyectos-Trabajo/directo_producciones_landing_page_1.0/content/facts.yaml')),'M1RecordsModified':False}
(out/'legacy-about-source.json').write_text(json.dumps(source,ensure_ascii=False,indent=2))
(root/'assets/brand-variants.json').write_text(json.dumps({'original':'logo-original.jpg','originalSha256':assets['logo']['originalSha256'],'whiteSource':'logo-white.svg','whiteImport':'logo-white.png','pngSha256':assets['logo']['pngSha256'],'method':'Máscara de luminancia sRGB del JPG original embebido sin cambios. Raster de 200×200, sin redibujar ni vectorizar letras. PNG transparente renderizado en Chrome desde esa máscara.','approval':'Autorización expresa de Jesús en el feedback de refinamiento: Directo blanco en todas las apariciones oscuras. No se inventa ID de decisión.','customerLogos':'16 archivos sin modificación/recoloración. Franja clara uniforme en el tema oscuro; SVG blanco TRH mantiene apoyo azul.','portraits':'Originales intactos. Recortes CSS por persona según refinements-01/crop-spec.json.'},ensure_ascii=False,indent=2))
plan={'status':'local_verified_pending_figma_in_place','targets':[{'key':key,'nodeId':id,'url':url(id),'operation':'Actualizar nodos existentes; no crear nuevas capturas/frames contenedores.','localSource':('index.html' if key.startswith('inicio-claro') else 'suite/'+('inicio' if key=='inicio-oscuro' else key)+'.html'),'changes':('Hero, enlaces de formato, marca blanca donde corresponda, franja de clientes y avatares' if key.startswith('inicio') else 'Explicaciones/destinos streaming y marca blanca' if key=='servicios' else 'Franja de logos y avatares; marca blanca' if key=='clientes' else 'Presentación editorial recuperada y composición nueva; marca blanca' if key=='quienes-somos' else 'Guía de marca blanca, crop de avatares, patrón de franja y destinos' if key=='guia' else 'Marca Directo blanca transparente en header/footer oscuros')} for key,id in frames.items()], 'unchanged':['Original 2:1841','Exploraciones 01 19:2 / 19:3–19:8','EmDash 52:2, sin logo de imagen y sin refinamiento visual solicitado'], 'intermediatesPendingCleanup':['28:2','30:2','31:2','34:2'], 'nativeInspectionRequired':['Obtener IDs hijos reales de cada contenedor al recuperar acceso','Cargar fuentes actuales antes de mutar texto/nodos','Editar en sitio y devolver IDs realmente afectados','Comprobar 16 logos, cifras 2400/169/7 y dos citas completas dentro del resultado Figma','Revisar capturas nativas desktop/mobile, claro/oscuro; reproducir o declarar estado de motion'], 'nativeMotion':'No configurado ni reproducido para esta iteración. Reacciones de enlaces a Servicios y anclas también pendientes de configuración nativa.', 'blockedOperation':'use_figma: actualización en sitio. El error Starter registrado en evidence/cleanup-api-result.json bloqueó la operación de escritura previa antes de ejecutar el código; no se vuelve a llamar solo para confirmar.', 'nativeVisualReview':'MCP screenshot/vídeo agotados; navegador invitado no dibuja el lienzo y Chrome limpio devuelve CloudFront 403, según evidencias previas. Sin nuevos intentos idénticos.', 'required':'Disponibilidad de use_figma y lectura/captura nativa, o sesión Figma con edición cuyo lienzo se renderice. No se requiere nueva autorización del usuario para estos cambios.', 'newCaptureIds':[], 'nativeWritesInThisRefinement':0}
(out/'figma-patch-plan.json').write_text(json.dumps(plan,ensure_ascii=False,indent=2))
state=load(root/'state.json')
state['refinements01']={'status':plan['status'],'scope':'Cuatro correcciones + logos en oscuro, destinos de formatos y contenido antiguo para Quiénes somos.','targetFrameIds':list(frames.values()),'localQA':{'views':len(qa),'failures':0,'navigationMotionScenarios':len(routes),'contrastPairs':len(contrast),'minimumTextContrast':round(min(p['ratio']for p in contrast),2),'avatarSize':80,'content':'16 logos / 2400,169,7 / dos citas completas exactas en Inicio y Clientes, todas sus vistas'},'nativeWrites':0,'nativeVerification':False,'newFrames':0,'evidence':'refinements-01/evidence','patchPlan':'refinements-01/figma-patch-plan.json','legacyCopy':'refinements-01/legacy-about-source.json','sourceHashes':{str(p.relative_to(root)):sha(p)for p in [root/'index.html',root/'desktop.html',root/'mobile.html',root/'prototype.js',out/'refinements.css',root/'suite/build-suite.py',root/'suite/build-guide.py',root/'suite/suite.js',root/'assets/logo-white.svg',root/'assets/logo-white.png']}}
state['completion']='Composiciones anteriores añadidas a Figma sin revisión nativa final. Refinamientos actuales corregidos y comprobados localmente, pendientes de aplicar EN SITIO a los IDs existentes. No se declara el encargo Figma completo.'
(root/'state.json').write_text(json.dumps(state,ensure_ascii=False,indent=2))
ledger=load(root/'suite/capture-ledger.json');ledger['refinements01']={'status':'pending_in_place_write_and_native_review','plan':'../refinements-01/figma-patch-plan.json','newCaptures':0,'historicalCaptureHashesPreserved':True}
for key,c in ledger['captures'].items():
 if key!='emdash':c['pendingRefinement']={'localSourceSha256':sha(root/c['source']),'capturedVersionUnchanged':True,'requiresInPlaceUpdate':True}
(root/'suite/capture-ledger.json').write_text(json.dumps(ledger,ensure_ascii=False,indent=2))
intro='''> **Refinamiento posterior — 8 de octubre:** cuatro correcciones y último feedback resueltos en las fuentes de diseño locales, con 78 vistas y rutas/motion comprobados. **No aplicados aún en Figma**: se mantienen los mismos IDs, sin nuevas capturas ni duplicados. Estado, evidencia y operación exacta pendiente en [refinements-01/ENTREGA.md](refinements-01/ENTREGA.md). La sección de importación siguiente describe la versión anterior añadida al archivo, no estas correcciones.

'''
p=root/'ENTREGA.md';text=p.read_text();marker='\n\nAlcance ampliado';text=text if intro in text else text.replace(marker,'\n\n'+intro+'Alcance ampliado',1)
text=text.replace('D-38: logo original 200×200 y portada corporativa, completos y sin recoloración.','D-38: logo original 200×200 y portada corporativa completos. En la versión previamente importada conservan el color original; el feedback posterior autoriza la variante blanca de Directo, preparada y comprobada en el refinamiento local pendiente de escritura Figma.')
p.write_text(text)
(out/'ENTREGA.md').write_text('''# Refinamiento 01 · Iteración 02 · estado real

Las correcciones están realizadas en las **fuentes locales de diseño**, sin tocar Astro, CMS ni registros M1. Se han comprobado en Chrome, escritorio/móvil y claro/oscuro. **Todavía no están aplicadas en Figma**. No se crea otro Inicio ni se emiten nuevas capturas.

- Hero: se elimina el rótulo gigante DIRECTO; título «Tu evento. En streaming.» y gráfico Evento → Realización → Emisión. Un solo gráfico en Inicio, con leyenda y etiquetas claras.
- Marca: Directo azul en claro; blanco transparente fiel al JPG en oscuro, header/footer y guía. Original intacto. [SVG fuente](../assets/logo-white.svg), [PNG transparente para importación](../assets/logo-white.png), [procedencia y método](../assets/brand-variants.json). Raster 200×200; no se presenta como logo vectorial definitivo. Las esquinas tienen alfa 0 y la tinta es blanca, sin rectángulo de fondo.
- Clientes en oscuro: franja clara uniforme para conservar colores y legibilidad; TRH blanco mantiene apoyo azul. Los 16 activos y nombres autorizados permanecen; no hay inversión de logos o fotografías.
- Avatares: círculo de 80×80 en todos los tamaños/temas. Recorte personalizado y escala óptica comparable: Rafael rostro de referencia ~34×53 px, José ~33×53 px. Medición orientativa manual complementada con revisión visual a tamaño real; retratos originales intactos. [Detalle desktop](evidence/clientes-light-desktop-testimonios.png) y [detalle móvil oscuro](evidence/clientes-dark-mobile-testimonios.png).
- Streaming: dos enlaces visibles «Ver formato». Eventos → Servicios / #servicios-streaming; TV online → Servicios / #tv-online. Explicaciones en una única página de Servicios; modo/dispositivo y fragmento conservados. Cabecera/footer de Inicio claro enlazan ya con las maquetas existentes; se elimina el aviso obsoleto de que esas páginas no están diseñadas. Son rutas probadas del prototipo local; las conexiones de prototipo Figma están pendientes de escritura.
- Quiénes somos: presentación «Un equipo. Varias formas de comunicar.» con texto sobre la productora, su equipo multidisciplinar y sus disciplinas. Composición editorial y cierre propio, sin repetir «Antes de emitir, hablemos». Texto recuperado/parafraseado de [Empresa en la web antigua](https://www.directoproducciones.com/quienes-somos/) por instrucción del propietario; borrador editorial en revisión, no validación nueva de facts ni afirmación de miembros de equipo inventados. [Procedencia y omisiones](legacy-about-source.json).

Se preservan íntegros D-42: **16 logos, 2400/169/7 y dos testimonios completos con atribuciones exactas**. D-40 mantiene aplazadas las fotos/vídeos de trabajos. No se inventan casos ni se reutilizan retratos de clientes como equipo. B5 sigue pendiente antes del lanzamiento.

## Evidencia comprobada

[Galería local de todas las vistas afectadas](index.html). Capturas reales de navegador, **no capturas Figma**: [Inicio desktop oscuro](evidence/inicio-dark-desktop.png), [Inicio móvil claro](evidence/inicio-claro-light-mobile.png), [Quiénes somos desktop claro](evidence/quienes-somos-light-desktop.png), [Quiénes somos móvil oscuro](evidence/quienes-somos-dark-mobile.png).

- 78 vistas a 1440/390/320 px: sin desbordamientos, imágenes ausentes ni errores JS; fuente Manrope cargada. Marca correcta en todas las apariciones inspeccionadas; retratos sin deformación. [Resultado](evidence/verification.json).
- 12 escenarios: ocho rutas de formato y vuelta a Inicio (ambos temas/dispositivos), cuatro de hero/menú/foco/Escape/reduced-motion. [Resultado](evidence/navigation-motion.json).
- 27 combinaciones reales de texto/superficie de los bloques afectados: mínimo 5.86:1. Los estados CTA/campos restantes conservan la comprobación anterior; no se pretende haber rehecho la auditoría integral de estados. [Contraste](evidence/contrast.json).
- Máscara de marca con original embebido idéntico byte a byte, proporción 1:1 y transparencia; ambos recortes a escala comparable. [Activos](evidence/assets-verification.json).

Motion se conserva: entrada opacity .84→1/translateY12→0, 480 ms, delays 0/80/160, cubic-bezier(.2,.8,.2,1); menú 220/180 ms con foco e inert; estados CTA 160/100 ms. «Ver formato» usa la misma flecha y transición 160 ms. Reduced-motion elimina desplazamientos y transiciones sin ocultar contenido; se comprueba el cambio de preferencia durante reproducción. Anclas sin scroll animado. Implementación solo en prototipo de diseño local CSS/WAAPI; **no implementado en Astro y no configurado/reproducido en Figma**. [Especificación conservada](../MOTION.md).

## Figma: mismos nodos, revisión pendiente

'''+ '\n'.join('- ['+key+' · '+id+']('+url(id)+')' for key,id in frames.items())+'''

Estos enlaces abren la **versión anterior** existente, no una sincronización de este refinamiento. Los IDs son contenedores reales devueltos por el importador; no se inventan IDs de sus hijos. [Plan de cambios en sitio](figma-patch-plan.json).

La operación pendiente es **actualizar los nodos existentes mediante use_figma y comprobar el resultado nativo**. La operación de escritura previa ya devolvió el límite MCP Starter antes de ejecutar código: [respuesta exacta](../evidence/cleanup-api-result.json). No se reintenta ese error para confirmarlo ni se recaptura por una vía que añadiría más frames. Captura/vídeo MCP siguen bloqueados en el estado documentado; el navegador invitado no dibuja el lienzo y Chrome limpio devolvió CloudFront 403. No se afirma revisión visual nativa ni reproducción nativa de motion.

Hace falta disponibilidad de edición/lectura MCP o una sesión Figma con edición que renderice el lienzo. La autorización del propietario ya existe; no se solicita de nuevo ni se contratan planes. Original 2:1841 y Exploraciones 01 19:2/19:3–19:8 intactos. EmDash 52:2 no se replantea. Los intermedios 28:2/30:2/31:2/34:2 continúan pendientes de limpieza por el mismo bloqueo.
''')
files=sorted(p.name for p in ev.glob('*.png'))
cards=''.join('<article><h2>'+html.escape(f.replace('.png','').replace('-',' '))+'</h2><a href="evidence/'+f+'"><img src="evidence/'+f+'" alt="Captura local: '+html.escape(f)+'" loading="lazy"></a><p><a href="evidence/'+f+'">Abrir a resolución original</a></p></article>'for f in files)
(out/'index.html').write_text('''<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Directo · Refinamiento · Evidencia local</title><style>body{font:16px/1.6 system-ui;margin:0;background:#F4F8FA;color:#172B34}main{max-width:1440px;margin:auto;padding:32px}h1{font-size:32px;line-height:1.2}.notice{padding:24px;background:#E5F0F4;border-left:4px solid #164E63}a{color:#164E63}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:32px;margin-top:32px}article{padding:24px;background:white;border:1px solid #D0DDE2}h2{font-size:18px;overflow-wrap:anywhere}img{display:block;width:100%;max-height:750px;object-fit:contain;object-position:top;background:#F4F8FA}a:focus-visible{outline:3px solid #164E63;outline-offset:4px}</style><main><h1>Directo · Refinamiento de las vistas existentes</h1><div class="notice"><strong>Capturas locales de navegador; cambios pendientes en Figma.</strong><p>No hay nuevas capturas/importaciones Figma ni duplicados. Esta galería muestra las correcciones alcanzables y comprobadas; los IDs nativos permanecen en su versión anterior hasta recuperar la escritura y revisión en sitio.</p><a href="ENTREGA.md">Estado, enlaces Figma y pruebas</a></div><p><a href="../index.html">Inicio claro local</a> · <a href="../suite/inicio.html?preview=1&theme=dark&device=desktop">Inicio oscuro local</a> · <a href="../suite/quienes-somos.html?preview=1&theme=light&device=desktop">Quiénes somos local</a> · <a href="../suite/guia.html?preview=1&theme=dark&device=desktop">Guía oscura local</a></p><div class="grid">'''+cards+'</div></main></html>')
print(json.dumps({'targets':len(frames),'nativeWrites':0,'views':len(qa),'scenarios':len(routes),'screenshots':len(files)},ensure_ascii=False))
