from pathlib import Path
import re,json,html
out=Path(__file__).parent;root=out.parent
home=(root/'index.html').read_text()
header=re.search(r'<header class="header".*?</header>',home,re.S).group()
footer=re.search(r'<footer class="footer.*?</footer>',home,re.S).group()
contact=re.search(r'<section class="contact section pad".*?</section>',home,re.S).group()
stream=re.search(r'<section class="streaming pad section".*?</section>',home,re.S).group()
metrics=re.search(r'<section class="metrics section pad".*?</section>',home,re.S).group()
testimonials=re.search(r'<section class="testimonials section pad".*?</section>',home,re.S).group()
process=re.search(r'<section class="process section pad".*?</section>',home,re.S).group()
mainhome=re.search(r'<main id="inicio">(.*?)</main>',home,re.S).group(1)
manifest=json.loads((root/'assets/manifest.json').read_text())
svg=lambda paths: '<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">'+paths+'</svg>'
icons={'arrow':svg('<path d="M7 17 17 7M7 7h10v10"/>'),'right':svg('<path d="M5 12h14m-6-6 6 6-6 6"/>'),'menu':svg('<path d="M4 8h16M4 16h16"/>'),'close':svg('<path d="m6 6 12 12M6 18 18 6"/>'),'phone':svg('<path d="M22 16.9v3a2 2 0 0 1-2.2 2A19.8 19.8 0 0 1 3.1 5.2 2 2 0 0 1 5.1 3h3a2 2 0 0 1 2 1.7c.1 1 .4 2 .8 3a2 2 0 0 1-.5 2.1L9.1 11a16 16 0 0 0 3.9 3.9l1.3-1.3a2 2 0 0 1 2.1-.5c1 .4 2 .7 3 .8a2 2 0 0 1 1.7 2Z"/>'),'mail':svg('<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/>'),'message':svg('<path d="M21 11.5a8.4 8.4 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.4 8.4 0 0 1-3.8-.9L3 21l1.9-5.7a8.4 8.4 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.4 8.4 0 0 1 3.8-.9h.5a8.5 8.5 0 0 1 8 8v.5Z"/>'),'sun':svg('<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M4.9 4.9l1.4 1.4m11.4 11.4 1.4 1.4M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/>'),'moon':svg('<path d="M21 12.8A9 9 0 1 1 11.2 3 7 7 0 0 0 21 12.8Z"/>'),'check':svg('<path d="m5 12 4 4L19 6"/>'),'alert':svg('<circle cx="12" cy="12" r="9"/><path d="M12 8v4m0 4h.01"/>')}
navpages=[('inicio','Inicio'),('servicios','Servicios'),('clientes','Clientes'),('quienes-somos','Quiénes somos'),('blog','Blog'),('contacto','Contacto')]
allpages=navpages+[('articulo','Artículo'),('404','404'),('cookies','Cookies'),('privacidad','Privacidad'),('aviso-legal','Aviso legal'),('emdash','EmDash interno')]
link=lambda key: key+'.html?preview=1'
def button(text,key='contacto',kind='primary'):return f'<a class="button {kind}" href="{link(key)}">{text} {icons["arrow"]}</a>'
def hero(kicker,title,copy,action=None):return '<section class="page-hero pad"><div><p class="eyebrow">'+kicker+'</p><h1>'+title+'</h1></div><div class="page-intro"><p>'+copy+'</p>'+(''+action if action else '')+'</div></section>'
def editorial_art(label='Streaming',word='DIRECTO'):return '<div class="editorial-art" aria-label="Gráfico editorial conceptual, no fotografía de trabajo"><span>'+label+'</span><strong>'+word+'</strong><span>Directo Producciones</span></div>'
def shell(body,key):
 h=header
 nav='<nav class="desktop-nav" aria-label="Principal">'+''.join('<a '+('class="active" aria-current="page" ' if k==key or (key=='articulo' and k=='blog') else '')+'href="'+link(k)+'">'+n+'</a>' for k,n in navpages[:-1])+'</nav>'
 h=re.sub(r'<nav class="desktop-nav".*?</nav>',nav,h,flags=re.S).replace('href="#inicio"','href="inicio.html?preview=1"').replace('href="#contacto"','href="contacto.html?preview=1"').replace('aria-controls="mobile-menu"','aria-controls="suite-menu"')
 f=footer
 replacements={'#inicio':'inicio','#streaming':'servicios','#colaboraciones':'clientes'}
 for a,b in replacements.items():f=f.replace('href="'+a+'"','href="'+link(b)+'"')
 for k,n in allpages:f=f.replace('<button data-destination="'+n+'">'+n+'</button>','<a href="'+link(k)+'">'+n+'</a>')
 menu='<nav class="suite-menu" id="suite-menu" aria-label="Principal móvil" hidden><div class="suite-menu-top"><strong>Directo Producciones</strong><button class="suite-menu-close" aria-label="Cerrar menú">'+icons['close']+'</button></div>'+''.join('<a href="'+link(k)+'">'+n+'</a>' for k,n in navpages)+'</nav>'
 return h+'<main>'+body+'</main>'+f+menu
service=hero('Servicios','Lo que necesitas<br>contar.','Streaming de eventos y realización televisiva. Comunicación y marketing digital para tu proyecto.','<a class="text-link" href="#servicios-streaming">Explora el streaming '+icons['right']+'</a>')
service+='<nav class="section-tabs pad" aria-label="Servicios en esta página"><a href="#servicios-streaming">Streaming</a><a href="#servicios-comunicacion">Comunicación</a><a href="#servicios-marketing">Marketing digital</a></nav>'
service+='<section id="servicios-streaming" class="service-feature pad"><div><p class="eyebrow">Streaming / El protagonista</p><h2>Del evento<br>a la pantalla.</h2><p>La retransmisión lleva lo que sucede en tu evento a una pantalla. La realización televisiva organiza cómo se presenta ese contenido.</p><div class="service-questions"><p>Eventos en streaming</p><p>TV online</p></div>'+button('Cuéntanos tu evento')+'</div>'+re.search(r'<div class="signal-stage signal-flow".*?</div></section>',home,re.S).group().replace('class="signal-stage signal-flow"','class="signal-stage signal-flow compact-flow"').removesuffix('</section>')+'</section>'
service+='<section id="tv-online" class="tv-format service-secondary section pad info-split"><div><p class="eyebrow">Streaming / TV online</p><h2>Un canal<br>para tu contenido.</h2></div><div><h3>TV online</h3><p>TV online y realización televisiva para emitir contenido online.</p><p>¿Qué quieres emitir? ¿Con qué programación? ¿En qué pantallas? Estas preguntas ayudan a definir tu canal.</p><a class="text-link" href="'+link('contacto')+'">Hablemos de tu TV online '+icons['arrow']+'</a></div></section>'
service+=metrics
service+='<section id="servicios-comunicacion" class="service-secondary section pad info-split"><div><p class="eyebrow">Comunicación</p><h2>Dar forma<br>al mensaje.</h2></div><div><h3>Comunicación corporativa</h3><p>Conversemos sobre el mensaje de tu organización y lo que necesitas comunicar.</p><div class="service-questions"><p>Comunicación corporativa</p><p>Gabinete de prensa</p></div><a class="text-link" href="'+link('contacto')+'">Hablemos de comunicación '+icons['arrow']+'</a></div></section>'
service+='<section id="servicios-marketing" class="service-secondary section pad info-split"><div><p class="eyebrow">Marketing digital</p><h2>La conversación<br>continúa.</h2></div><div><h3>Tu proyecto en digital</h3><p>Exploremos la presencia digital de tu proyecto y los canales que necesitas trabajar.</p><div class="service-questions"><p>Marketing digital</p><p>Redes sociales</p></div><a class="text-link" href="'+link('contacto')+'">Cuéntanos qué necesitas '+icons['arrow']+'</a></div></section>'+contact
clients=hero('Clientes','En buena<br>compañía.','Instituciones, empresas y marcas que forman parte de la trayectoria de Directo Producciones.')+'<section class="pad section client-logo-band" style="padding-top:32px"><div class="client-directory">'
for a in manifest:clients+='<figure class="directory-cell"><div class="directory-logo '+('logo-dark' if a['file'].endswith('hotel_motilla.svg') else '')+'"><img src="'+a['file']+'" alt="'+html.escape(a['name'])+'"></div><figcaption>'+html.escape(a['name'])+'</figcaption></figure>'
clients+='</div></section>'+metrics+testimonials+contact
about=hero('Quiénes somos','Directo<br>Producciones.','Una productora de streaming, comunicación y marketing digital.')
about+='<section class="about-editorial section pad" data-section="Quiénes somos · presentación de la productora"><div class="about-company-heading"><div><p class="eyebrow">La productora</p><h2>Un equipo.<br>Varias formas<br>de comunicar.</h2></div><div class="about-company-copy"><p class="about-lead">Somos una productora especializada en la retransmisión de eventos en streaming.</p><p>Directo Producciones reúne un equipo multidisciplinar dedicado a la comunicación y al marketing digital.</p><p>La realización televisiva, la comunicación de una organización y su presencia digital forman parte de nuestra actividad.</p></div></div><div class="about-practices"><div class="about-practices-intro"><h3>Qué hacemos<br>desde la productora.</h3><p>El streaming es el punto de partida. La comunicación y el marketing amplían las formas de trabajar el mensaje.</p><a class="text-link" href="'+link('servicios')+'">Conoce nuestros servicios '+icons['arrow']+'</a></div><div class="practice-lines"><div class="practice-line"><span>01</span><div><h3>Streaming y realización</h3><p>Retransmisión de eventos y TV online con realización televisiva.</p></div></div><div class="practice-line"><span>02</span><div><h3>Comunicación corporativa</h3><p>Comunicación de organizaciones y gabinete de prensa.</p></div></div><div class="practice-line"><span>03</span><div><h3>Marketing digital</h3><p>Redes sociales, SEO, SEM, diseño publicitario y gestión de marca.</p></div></div></div></div><p class="team-pending">Borrador editorial recuperado de la web actual para revisión. Nombres, funciones y fotografías del equipo pendientes de aprobación.</p></section>'
about+=contact.replace('De la idea a la emisión','Contacto').replace('¿Qué tienes<br>en mente?','Conversemos<br>sobre tu proyecto.').replace('Cuéntanos el evento que estás preparando.','Streaming, comunicación o marketing digital. Cuéntanos qué necesitas.')
blog=hero('Blog','Lo que<br>contamos.','Un espacio editorial para el streaming, la comunicación y el marketing digital.')+'<section class="pad blog-feature"><div>'+editorial_art('Plantilla editorial')+'</div><div><p class="blog-meta">[Categoría] · [Fecha]</p><h2>[Título del artículo destacado]</h2><p>[Entradilla del artículo. El texto real se incorporará cuando tenga revisión editorial.]</p><a href="'+link('articulo')+'" class="text-link">Leer artículo '+icons['arrow']+'</a></div></section><section class="section pad" style="padding-top:32px"><p class="eyebrow">Más artículos</p><div class="blog-list">'
for i in range(2):blog+='<article class="blog-row"><p class="blog-meta">[Categoría]<br>[Fecha]</p><h3><a href="'+link('articulo')+'">[Título del artículo]</a></h3><a class="circle-link" href="'+link('articulo')+'" aria-label="Abrir plantilla de artículo">'+icons['arrow']+'</a></article>'
blog+='</div><div class="blog-empty">Estado alternativo sin publicaciones: «Todavía no hay artículos publicados».</div></section>'+contact
article='<nav class="breadcrumb pad" aria-label="Ruta de navegación"><a href="'+link('blog')+'">Blog</a><span>/</span><span>Artículo</span></nav><section class="article-hero pad"><p class="eyebrow">[Categoría] / Plantilla editorial</p><h1>[Título del<br>artículo]</h1><p class="blog-meta">[Autor] · [Fecha de publicación]</p></section><div class="pad">'+editorial_art('Imagen editorial pendiente · sin fotografías de trabajos')+'</div><div class="article-layout pad"><nav class="article-toc" aria-label="En este artículo"><strong>En este artículo</strong><a href="#articulo-intro">Introducción</a><a href="#articulo-seccion">[Sección del artículo]</a><a href="#articulo-cierre">[Cierre del artículo]</a></nav><article class="article-body"><p id="articulo-intro">[Entradilla del artículo. El texto debe presentar el tema y ofrecer una primera idea clara, sin claims ni cifras pendientes de aprobación.]</p><p>[Primer párrafo del artículo. Campo editorial pendiente de incorporar. La maqueta fija el ancho de lectura y la separación entre párrafos.]</p><h2 id="articulo-seccion">[Subtítulo del artículo]</h2><p>[Texto de la sección. Contenido pendiente de revisión editorial.]</p><blockquote>[Cita destacada del artículo, solo cuando forme parte del contenido aprobado.]</blockquote><p>[Párrafo posterior a la cita, pendiente de contenido aprobado.]</p><h2 id="articulo-cierre">[Cierre del artículo]</h2><p>[Texto final del artículo. Pendiente de incorporar y revisar.]</p><a class="text-link" href="'+link('blog')+'">Volver al blog '+icons['right']+'</a></article></div>'
contactpage=hero('Contacto','¿Qué tienes<br>en mente?','Cuéntanos el evento o el proyecto que estás preparando.')+'<section class="contact-layout pad"><div class="contact-methods">'
for title,value,icon in [('Llámanos','679 729 727','phone'),('WhatsApp','622 181 100','message'),('Escríbenos','info@directoproducciones.com','mail')]:contactpage+='<button class="contact-method" data-demo="Método de contacto especificado; no se activa captación en este prototipo">'+icons[icon]+'<h2>'+title+'</h2><span>'+value+'</span></button>'
contactpage+='</div><form class="contact-form" data-design-form novalidate><h2>Hablemos de tu proyecto.</h2><div class="field-grid"><div class="field"><label for="name">Nombre *</label><input id="name" name="name" autocomplete="name" placeholder="Tu nombre" required></div><div class="field"><label for="email">Email *</label><input id="email" name="email" type="email" autocomplete="email" placeholder="tu@email.com" required></div></div><div class="field-grid"><div class="field"><label for="phone">Teléfono</label><input id="phone" name="phone" type="tel" autocomplete="tel" placeholder="Opcional"></div><div class="field"><label for="company">Organización</label><input id="company" name="company" autocomplete="organization" placeholder="Opcional"></div></div><div class="field"><label for="service">¿Sobre qué hablamos?</label><select id="service" name="service"><option>Streaming</option><option>Comunicación</option><option>Marketing digital</option></select></div><div class="field"><label for="message">Tu proyecto *</label><textarea id="message" name="message" required placeholder="Cuéntanos qué estás preparando"></textarea><p class="help">Los campos con * son obligatorios.</p></div><label class="check-label"><input type="checkbox" name="privacy" required><span>He leído la <a href="'+link('privacidad')+'">política de privacidad</a>.</span></label><button type="submit" class="button primary">Enviar consulta '+icons['arrow']+'</button><p class="form-status" role="status">Prototipo de diseño: no se envían ni guardan datos.</p></form></section>'
error='<section class="error-page pad"><div><p class="eyebrow">Algo se ha quedado fuera de señal</p><p class="error-number">404</p></div><div><h1>Esta página<br>no está aquí.</h1><p>Puedes volver a Inicio o contarnos lo que necesitas.</p>'+button('Volver a Inicio','inicio')+'<br><a class="text-link" href="'+link('contacto')+'">Ir a Contacto '+icons['arrow']+'</a></div></section>'
legaldef={'cookies':('Política<br>de cookies.',['Información general','Inventario de cookies','Tus preferencias']),'privacidad':('Política<br>de privacidad.',['Responsable','Finalidades y base jurídica','Conservación y destinatarios','Tus derechos']),'aviso-legal':('Aviso<br>legal.',['Identificación del titular','Condiciones de uso','Propiedad intelectual','Responsabilidad y contacto'])}
legal={}
for key,(title,sections) in legaldef.items():
 body=hero('Información legal',title,'[Fecha de actualización y texto legal pendientes de revisión vigente.]')+'<div class="legal-layout pad"><nav class="legal-index" aria-label="Contenido">'+''.join('<a href="#legal-'+str(i)+'">'+n+'</a>' for i,n in enumerate(sections))+'</nav><article class="legal-content"><p class="legal-status">Plantilla de diseño. El texto jurídico se incorporará tras su revisión y aprobación; no se reproduce la política antigua.</p>'
 for i,n in enumerate(sections):body+='<h2 id="legal-'+str(i)+'">'+n+'</h2><p>[Contenido de esta sección pendiente de revisión y aprobación.]</p>'
 if key=='cookies':body+='<table class="legal-table"><thead><tr><th>Nombre</th><th>Finalidad</th><th>Duración</th></tr></thead><tbody><tr><td>[Cookie]</td><td>[Finalidad verificada]</td><td>[Duración]</td></tr></tbody></table><div class="preferences-demo"><h3>Preferencias de cookies</h3><div class="preference-row"><span>Necesarias<br><small>Siempre activas</small></span><span class="status-chip">Obligatorias</span></div><div class="preference-row"><span>[Categoría opcional]<br><small>Solo si existe y está aprobada</small></span><button class="toggle off" aria-label="Categoría opcional desactivada" aria-pressed="false" data-toggle-demo></button></div><button class="button primary" data-demo="Estado de preferencias: demostración sin cookies opcionales ni tracking">Guardar preferencias</button></div>'
 body+='</article></div>';legal[key]=body
cms='<div class="cms-shell"><aside class="cms-nav"><h2>EmDash</h2><p>Directo Producciones · Blog</p><nav aria-label="Área editorial"><a href="#cms-articulos" class="active">Artículos</a><a href="#cms-editor">Editor</a><a href="#cms-revision">Revisión editorial</a></nav></aside><main class="cms-main"><div class="cms-top"><span>Área interna / Blog</span><button data-demo="Cierre de sesión: estado de diseño sin sesión real">Cerrar sesión</button></div><div class="cms-title"><h1>Artículos</h1><a class="button primary" href="#cms-editor">Nuevo borrador '+icons['arrow']+'</a></div><p class="cms-sub">Prepara contenido, guarda el borrador y solicita revisión.</p><section id="cms-articulos" class="cms-list"><div class="cms-list-head"><span>Título</span><span>Estado</span><span>Acción</span></div><div class="cms-list-item"><span>[Título del borrador]</span><span class="status-chip">Borrador</span><a href="#cms-editor">Editar</a></div><div class="cms-list-item"><span>[Título del artículo en revisión]</span><span class="status-chip">En revisión</span><a href="#cms-revision">Ver revisión</a></div></section><section class="cms-editor" id="cms-editor"><h2>Nuevo artículo</h2><div class="field"><label for="cms-title">Título</label><input id="cms-title" placeholder="Título del artículo"></div><div class="field"><label for="cms-slug">URL del artículo</label><input id="cms-slug" placeholder="titulo-del-articulo"><p class="help">/blog/[slug]</p></div><div class="field"><label for="cms-excerpt">Entradilla</label><textarea id="cms-excerpt" placeholder="Resumen editorial"></textarea></div><div class="field"><label>Contenido</label><div class="editor-toolbar" aria-label="Formato de texto"><button aria-label="Negrita"><b>B</b></button><button aria-label="Cursiva"><i>I</i></button><button aria-label="Encabezado">H2</button><button aria-label="Añadir enlace">'+icons['right']+'</button></div><div class="editor-content">[Contenido del borrador]</div></div><div class="cms-actions"><button class="button primary" data-demo="Borrador guardado: estado visual, sin persistencia real">Guardar borrador</button><button class="button secondary-button" data-demo="Solicitud de revisión: estado visual, sin notificaciones reales">Solicitar revisión</button></div></section><section id="cms-revision" class="cms-editor"><h2>Revisión editorial</h2><p class="cms-sub">Antes de publicar: revisión del texto exacto, hechos y derechos de las piezas.</p><table class="legal-table"><tbody><tr><th>Texto</th><td>Pendiente de revisión</td></tr><tr><th>Hechos y cifras</th><td>Referencias a facts aprobados</td></tr><tr><th>Medios</th><td>Evidencia de derechos</td></tr><tr><th>Publicación</th><td>Solo persona autorizada</td></tr></tbody></table></section></main></div>'
content={'inicio':mainhome,'servicios':service,'clientes':clients,'quienes-somos':about,'blog':blog,'articulo':article,'contacto':contactpage,'404':error,**legal,'emdash':cms}
notes={'inicio':'Inicio claro definitivo: Figma 35:2 / 37:2. Esta ficha solo sincroniza Inicio oscuro; no se vuelve a importar Inicio claro.','servicios':'Una sola página de Servicios. Streaming protagonista; comunicación y marketing presentes. Alcance de servicios sigue pendiente de confirmación de facts.','clientes':'16 nombres según social_proof.home_clients; cifras y testimonios completos aprobados por D-42.','quienes-somos':'Logo y portada completos autorizados en D-38. Presentación editorial recuperada de Empresa en la web actual por instrucción del propietario, en revisión. Equipo detallado y medios pendientes de aprobación.','blog':'Plantilla de listado y estado sin publicaciones. Ninguna entrada real aprobada en el registro editorial.','articulo':'Plantilla de artículo: jerarquía, lectura, metadata y navegación. Sin atribuir artículos ni autores ficticios.','contacto':'Cuatro métodos acordados por D-23. Contactos decided, aprobación para republicación pendiente. Formulario local de diseño, sin envío, leads, SLA ni integraciones.','404':'Recuperación hacia Inicio y Contacto; sin promesas técnicas.','cookies':'Estructura legal pendiente de contenido revisado. Preferencias visuales de ejemplo, sin cookies ni analítica activadas.','privacidad':'Estructura y ancho de lectura; no se inventan bases, plazos, encargados ni responsables.','aviso-legal':'Campos jurídicos pendientes de aprobación; no se copia el aviso antiguo.','emdash':'Área interna para el blog. Propuesta visual; no se reemplaza ni modifica el CMS existente ni se presenta publicación/roles como implementados.'}
nav='<nav>'+''.join('<a href="'+k+'.html">'+n+'</a>' for k,n in allpages)+'<a href="guia.html">Guía de estilos</a></nav>'
head=lambda title:'<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Directo · M4 · '+title+'</title><link rel="stylesheet" href="../style.css"><link rel="stylesheet" href="suite.css"><link rel="stylesheet" href="../refinements-01/refinements.css"><script defer src="suite.js"></script><script src="https://mcp.figma.com/mcp/html-to-design/capture.js" async></script></head><body>'
for key,name in allpages:
 inner=content[key] if key=='emdash' else shell(content[key],key)
 # Contacts in reusable Home closing point to the designed route, never external leads.
 inner=re.sub(r'<button class="button light" data-destination="Contacto">(.*?)</button>',lambda m:'<a class="button light" href="'+link('contacto')+'">'+m.group(1)+'</a>',inner,flags=re.S)
 inner=inner.replace('src="assets/','src="../assets/').replace('href="suite/','href="')
 themes=['dark'] if key=='inicio' else ['light','dark']
 screens=[]
 for theme in themes:
  cards=[]
  for device,width in [('desktop',1440),('mobile',390)]:
   prefix=key+'-'+theme+'-'+device+'-'
   body=inner
   ids=re.findall(r'\bid="([^"]+)"',body)
   for id in sorted(set(ids),key=len,reverse=True):
    body=body.replace('id="'+id+'"','id="'+prefix+id+'"').replace('for="'+id+'"','for="'+prefix+id+'"').replace('href="#'+id+'"','href="#'+prefix+id+'"').replace('aria-controls="'+id+'"','aria-controls="'+prefix+id+'"')
   cards.append('<section class="screen-wrap" data-theme="'+theme+'" data-device="'+device+'" data-page="'+key+'"><p class="screen-label">'+name+' / '+('Oscuro' if theme=='dark' else 'Claro')+' / '+('Escritorio 1440' if device=='desktop' else 'Móvil 390')+'</p><div class="artboard" style="width:'+str(width)+'px"><div class="design-surface '+('theme-dark' if theme=='dark' else '')+'" aria-label="'+name+' · '+theme+' · '+device+'">'+body+'</div></div></section>')
  screens.append('<div class="theme-row">'+''.join(cards)+'</div>')
 page=head(name)+'<aside class="suite-index"><h1>Directo · M4</h1><p>Maquetas para revisión. No se publica ni implementa el sitio.</p>'+nav+'</aside><div id="capture-root" class="capture-board"><div class="board-heading"><h1>'+name+' · Sistema La señal</h1><p>'+notes[key]+'</p></div>'+''.join(screens)+'</div><dialog id="suite-dialog"><h2>Estado del prototipo</h2><p></p><button class="button primary" data-close-demo>Volver al diseño</button></dialog></body></html>'
 (out/(key+'.html')).write_text(page)
old_index=(out/'index.html').read_text() if (out/'index.html').exists() else ''
figma_links=re.search(r'<section style="margin-top:48px">.*?</section>',old_index,re.S)
(out/'index.html').write_text(head('Índice de entrega')+'<div class="suite-index"><h1>Directo · M4 · Sistema La señal</h1><p>Páginas claras/oscuras y escritorio/móvil. No incluye copias de Inicio claro definitivo (35:2 / 37:2). Cada vista tiene un registro único de captura para evitar duplicados.</p>'+nav+(figma_links.group() if figma_links else '')+'</div></body></html>')
(out/'inventory.json').write_text(json.dumps({'pages':[{'key':k,'name':n,'themes':['dark'] if k=='inicio' else ['light','dark'],'devices':['desktop','mobile'],'content_note':notes[k]}for k,n in allpages],'native_components':'Pending: cuota use_figma agotada. Guía visual editable no equivale a modos/variables y componentes vinculados.'},ensure_ascii=False,indent=2))
(out/'icons.json').write_text(json.dumps(icons,ensure_ascii=False,indent=2))
print('12 páginas: Inicio oscuro + 11 páginas claro/oscuro; desktop/mobile; fuentes y datos comunes.')
